export const jobsActionTypes = {
  FETCH_ALL_JOBS: "FETCH_ALL_JOBS",
  FETCH_ALL_JOBS_USER_POSTED: "FETCH_ALL_JOBS_USER_POSTED",
  FETCH_ALL_JOBS_USER_BIDDED: "FETCH_ALL_JOBS_USER_BIDDED",
  FETCH_ALL_JOBS_USER_FINISHED: "FETCH_ALL_JOBS_USER_FINISHED",
  FETCH_SINGLE_JOB: "FETCH_SINGLE_JOB",
  FETCH_SINGLE_JOB_BY_COMPLETED_JOB: "FETCH_SINGLE_JOB_BY_COMPLETED_JOB",
  COMPLETE_JOB: "COMPLETE_JOB",
  CREATE_JOB: "CREATE_JOB",
  EDIT_JOB: "EDIT_JOB",
  SEARCH_JOBS_BY_WORD_AND_TECH:"SEARCH_JOBS_BY_WORD_AND_TECH"
};
export const bidsActionTypes = {
  FETCH_ALL_BIDS: "FETCH_ALL_BIDS",
  FETCH_BIDS_BY_JOB: "FETCH_BID_BY_JOB",
  FETCH_BIDS_BY_JOB_AND_USER: "FETCH_BID_BY_JOB_AND_USER",
  BID_FOR_JOB: "BID_FOR_JOB",
  REMOVE_BID: "REMOVE_BID",
  UPDATE_BID: "UPDATE_BID",
  EMPTY_BID: "EMPTY_BID",
};

export const usersActionTypes = {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_USER: "GET_USER",
  USER_ERRORS: "USER_ERRORS",
};

export const technologiesActionTypes = {
  FETCH_ALL_TECHNOLOGIES: "FETCH_ALL_TECHNOLOGIES",
  FETCH_TECHNOLOGIES_BY_JOB: "FETCH_TECHNOLOGIES_BY_JOB",
  EMPTY_TECHNOLOGIES_BY_JOB: "EMPTY_TECHNOLOGIES_BY_JOB",
  FETCH_TECHNOLOGIES_BY_USER: "FETCH_TECHNOLOGIES_BY_USER",
  ATTACH_TECHNOLOGY_TO_USER: "ATTACH_TECHNOLOGY_TO_USER",
  DETACH_TECHNOLOGY_FROM_USER: "DETACH_TECHNOLOGY_FROM_USER",
  ATTACH_TECHNOLOGY_TO_JOB: "ATTACH_TECHNOLOGY_TO_JOB",
  DETACH_TECHNOLOGY_FROM_JOB: "DETACH_TECHNOLOGY_FROM_JOB",
  FETCH_SINGLE_TECHNOLOGY: "FETCH_SINGLE_TECHNOLOGY",
  CREATE_TECHNOLOGY: "CREATE_TECHNOLOGY",
};

export const freelancersActionTypes = {
  FETCH_ALL_FREELANCERS: "FETCH_ALL_FREELANCERS",
  FETCH_SINGLE_FREELANCER: "FETCH_SINGLE_FREELANCER",
  FETCH_FREELANCERS_FOR_INBOX: "FETCH_FREELANCERS_FOR_INBOX",
  SEARCH_FREELANCERS_BY_WORD_AND_TECH: "SEARCH_FREELANCERS_BY_WORD_AND_TECH",
  GET_UNREAD_MESS_FOR_FREELANCER: "GET_UNREAD_MESS_FOR_FREELANCER",
  UPDATE_FREELANCER: "UPDATE_FREELANCER",
  CHOOSE_FREELANCER_FOR_MESSAGE: "CHOOSE_FREELANCER_FOR_MESSAGE",
  REMOVE_FREELANCER_FOR_MESSAGE: "REMOVE_FREELANCER_FOR_MESSAGE",
};
export const chargesActionTypes = {
  FETCH_ALL_CHARGES: "FETCH_ALL_CHARGES",
  FETCH_ALL_CHARGES_BY_USER_ID: "FETCH_ALL_CHARGES_BY_USER_ID",
  CREATE_CHARGE: "CREATE_CHARGE",
  SEARCH_CHARGES_BY_STATUS_WORD_AND_AMOUNT: "SEARCH_CHARGES_BY_STATUS_WORD_AND_AMOUNT",
  ACCEPT_CHARGE: "ACCEPT_CHARGE",
  DECLINE_CHARGE: "DECLINE_CHARGE",
  REFRESH_CHARGES: "REFRESH_CHARGES",
  GET_UNCHECKED_CHARGES: "GET_UNCHECKED_CHARGES",
  GET_ADMIN_CHARGES_NUMBER: "GET_ADMIN_CHARGES_NUMBER",
  CHECK_CHARGE: "CHECK_CHARGE",
};